# Arquivo: render.yaml

services:
  # Serviço 1: Backend Java (Web Service)
  - type: web
    name: advocacia-api # Nome para o seu backend
    runtime: java # <<< AQUI definimos o ambiente como JAVA!
    repo: https://github.com/dansantos14/advocacia-app.git # Opcional, mas bom ter
    rootDir: backend # Diretório raiz do backend
    buildCommand: "mvn clean package"
    startCommand: "java -jar target/advocacia-danilo-atualizado-0.0.1-SNAPSHOT.jar"
    plan: free # Define o plano gratuito
    envVars:
      - key: DATABASE_URL # Variável de ambiente para a URL do banco de dados
        fromDatabase:
          name: advocacia-db # Nome do serviço de banco de dados (definido abaixo)
          property: connectionString

  # Serviço 2: Frontend React (Static Site)
  - type: static
    name: advocacia-frontend # Nome para o seu frontend
    repo: https://github.com/dansantos14/advocacia-app.git
    rootDir: frontend # Diretório raiz do frontend
    buildCommand: "npm run build"
    publishDir: dist # Pasta que será publicada após o build

  # Serviço 3: Banco de Dados PostgreSQL
  - type: pserv # pserv = PostgreSQL Server
    name: advocacia-db # Nome do banco de dados
    plan: free
